### PR TITLE
Working

### PR DESCRIPTION
**Pull request by BSGreaves**
I believe this one is ready for feedback too. Thanks!

### CODE REVIEW

**Comment by morecallan** [comment]
@BSGreaves - your project is next to perfect. I like that you have a defineTree with validation.

The only thing that needs to be changed is that there should only be one console log output that spits out the whole tree, not multiple console logs that spit out each line.

**Comment by morecallan** [comment]
Oh, and if you really want a nice validation, check to make sure the user enters a valid number in the height field... 

not a necessity but if you are bored with TreeHouse over there...

**Comment by BSGreaves** [comment]
@morecallan Changes made. Now uses a single console.log with line breaks. Number validation improved. Thx.

**Comment by morecallan** [comment]
👍  beautiful!

**Pull request merged**
